name: yourcorporation
version: '3.9'

services:
  bootstrapper:
    container_name: YourCorporation_Bootstrapper
    build:
      context: .
      dockerfile: src/Bootstrapper/YourCorporation.Bootstrapper/Dockerfile
    depends_on:
      - mssql-db
      - rabbitmq 
    restart: on-failure
    ports:
      - "8081:80"
      - "8082:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro

  mssql-db:
    container_name: YourCorporation_MSSQL
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    volumes:
      - .datamssql/data:/var/opt/mssql/data
      - .datamssql/log:/var/opt/mssql/log
      - .datamssql/secrets:/var/opt/mssql/secrets

  rabbitmq:
    container_name: YourCorporation_RabbitMQ
    image: rabbitmq:3-management
    hostname: YourCorporation_RabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - yourcorporation_rabbitmq_queue_data:/var/lib/rabbitmq
      - yourcorporation_rabbitmq_queue_logs:/var/log/rabbitmq rabbitmq:3-management

  keycloak_web:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak_web
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - keycloak_db

  keycloak_db:
    image: postgres:16.2
    container_name: keycloak_db
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}

volumes:
  yourcorporation_rabbitmq_queue_data:
  yourcorporation_rabbitmq_queue_logs:
  keycloak_postgres_data:
    driver: local